In [6]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
l=range(1000)
%timeit [i**2 for i in l]

69.4 μs ± 1.69 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
a= np.arange(1000)
%timeit a**2

1.31 μs ± 43.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
a=np.array([1,2,3,4])
print(a.ndim)

1


In [23]:
b=np.array([[1,2,3],[4,5,6]])
print(a.ndim)

3


In [24]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.ndim)

3


shape

In [25]:
print(c.shape)

(2, 2, 2)


In [26]:
print(a.shape)

(2, 2, 2)


functions for creating  array

In [28]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


using linspace


In [31]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [32]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [37]:
print(np.diag(a))

[1 2 3 4]


basic datatypes

In [2]:
import numpy as np
a = np.arange(10)
print(a.dtype)

int64


In [3]:
a=np.arange(10,dtype="float64")
print(a.dtype)

float64


other datatype


In [4]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [6]:
a=np.array([True,False])
print(a.dtype)

bool


In [7]:
a=np.array(['hima','nanna'])
print(a.dtype)

<U5


indexing and slicing

In [8]:
a=np.arange(10)
print(a[4])

4


In [9]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [11]:
a=np.diag([1,2,3])
print(a[2,1])

0


slicing

In [12]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(a[1:8:2])

[1 3 5 7]


copies and viewing


In [14]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [15]:
print(np.shares_memory(a,b))

True


In [16]:
b[0]=10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [17]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [18]:
print(np.shares_memory(a,b))

False


In [19]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


random number generator

In [20]:
a=np.random.randint(0,20,15)
print(a)

[ 7 10 12 11 19 17  2 16 19  4 10 12  7 15 18]


element wise operations


In [21]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [22]:
print(a**2)


[ 1  4  9 16]


OPERATORS


b=np.ones(4)+1
print("a=",a)
print("b=",b)


In [30]:
b=np.ones(4)+1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [31]:
print(a*b)

[2. 4. 6. 8.]


comparsion operator

In [34]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a==b)

[False False False False]


In [35]:
print(a>b)

[False False False False]


In [36]:
print(a<b)

[ True  True  True  True]


In [40]:
#Array wise comparison

In [43]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))


False


logical operators

In [45]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True  True False]


In [46]:
print(np.logical_and(a,b))

[ True False False False]


trigonometry functions

In [47]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [48]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


basic reductions

In [50]:
x=np.array([[1,2],[1,2]])
print(x)

[[1 2]
 [1 2]]


In [51]:
x.sum(axis=0)

array([2, 4])

In [52]:
x.sum(axis=1)

array([3, 3])

other reductions

In [ ]:
x=np